version: '3'
services:
  
  zookeeper-1:
    image: confluentinc/cp-zookeeper:5.5.0
    container_name: zookeeper-1
    hostname: zookeeper-1
    restart: always
    environment:
        ZOO_MY_ID: 1
        ZOOKEEPER_SERVER_ID: 1
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
        ZOO_SERVERS: server.1=zookeeper-1:2888:3888
        ZOO_LOG4J_PROP: "INFO,CONSOLE,ROLLINGFILE"
    ports:
      - "2181:2181"
    volumes:
      - ./zk-single-kafka-single/zookeeper-1/conf:/conf
      - ./zk-single-kafka-single/zookeeper-1/logs:/logs
      - ./zk-single-kafka-single/zookeeper-1/data:/var/lib/zookeeper/data
      - ./zk-single-kafka-single/zookeeper-1/datalog:/var/lib/zookeeper/log/
  
  kafka-1:
    image: confluentinc/cp-kafka:5.5.0
    hostname: kafka-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-1:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:29092,PLAINTEXT_HOST://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - ./zk-single-kafka-single/kafka-1/data:/var/lib/kafka/data
    depends_on:
      - zookeeper-1